#!/bin/bash
# -------------------------------------------------
# Script Name  :  MoeArt Maid-Chan startup script
# Script Author:  MoeArt Development Team
# Description  :  The init script of maid-chan
# Build Date   :  Nov, 6th 2016 Sun
# -------------------------------------------------

# Starting up PHP and NGINX engine
/etc/init.d/php5-fpm start
nginx -g "daemon off;"