#!/bin/bash
# -------------------------------------------------
# Script Name  :  MoeArt Maid-Chan startup script
# Script Author:  MoeArt Development Team
# Description  :  The init script of maid-chan
# Build Date   :  June, 13th 2018 Wed
# -------------------------------------------------

# Starting up Cron
/etc/init.d/cron start

# Starting up PHP and NGINX engine
/etc/init.d/php7.0-fpm start
nginx -g "daemon off;"
